### ISSUE TITLE
Is sweepea using sqlite3_close_v2 ?

### ISSUE THREAD

**Issue by adiroiban** [coleifer/sweepea#1]
Hi,

Thanks for creating and making this project public.

I have not yet used it...and I might not use it after all.

I am not familiar with cython...so I could not found the answer myself.

I just wanted to ask if sweepea using the sqlite3_close_v2 method.
  
https://sqlite.org/c3ref/close.html

This is similar to what is done here 
https://github.com/coleifer/pysqlite3/blob/cab5dc24b344303f8ea5a5142d996b54dd2c9cff/src/util.h#L43

Thanks again for your work!

PS: I know that is a personal project... if you want other to use it, it might help to provide a comparison benchmark and ... windows wheels would be super :)
But don't do it just for me. My plan is to move my sqlite handling code to golang

**Comment by coleifer** [comment]
Its using the stdlib sqlite3 driver, which transitioned to sqlite3_close_v2 here:

https://github.com/python/cpython/pull/359

**Comment by adiroiban** [comment]
Many thanks for your response. Now it make sense.
I will look into using https://github.com/coleifer/pysqlite3 as it looks awesome :)
